name: barcode_plus
description: >-
  Barcode generation library for Dart that can generate
  generic drawing operations for any backend.
homepage: https://github.com/kechankrisna/dart_barcode/tree/master/barcode
repository: https://github.com/kechankrisna/dart_barcode
issue_tracker: https://github.com/kechankrisna/dart_barcode/issues
version: 3.0.0

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  meta: ^1.7.0
  qr: ^4.0.0

dev_dependencies:
  convert: ^3.0.1
  flutter_lints: ^6.0.0
  test: ^1.19.0
